import {
  AlertTriangle,
  BadgeCheck,
  Ban,
  BarChart3,
  Bookmark,
  BookmarkCheck,
  Building2,
  Calculator,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Cpu,
  Download,
  Eye,
  EyeOff,
  Factory,
  FileCheck,
  FileInput,
  FilePlus,
  FileSearch,
  FileSpreadsheet,
  FileText,
  FileWarning,
  Gift,
  GitBranch,
  Globe,
  Handshake,
  HardHat,
  Heart,
  Landmark,
  Link2,
  LogIn,
  LogOut,
  Megaphone,
  Menu,
  Package,
  Percent,
  Phone,
  PieChart,
  Printer,
  Receipt,
  Scale,
  Search,
  Settings,
  Shield,
  Ship,
  ShoppingCart,
  Sparkles,
  User,
  UserRound,
  Users,
  UsersRound,
  Wallet,
  X,
  XCircle,
  Maximize2,
  Minimize2,
  RotateCcw,
  ZoomIn,
  ZoomOut,
} from 'lucide-react'

const MAP = {
  scale: Scale,
  receipt: Receipt,
  'file-text': FileText,
  'bar-chart': BarChart3,
  building: Building2,
  'badge-check': BadgeCheck,
  clipboard: ClipboardList,
  'pie-chart': PieChart,
  wallet: Wallet,
  user: User,
  landmark: Landmark,
  globe: Globe,
  ship: Ship,
  package: Package,
  users: Users,
  calculator: Calculator,
  folder: FileText,
  heart: Heart,
  handshake: Handshake,
  shield: Shield,
  megaphone: Megaphone,
  'alert-triangle': AlertTriangle,
  'git-branch': GitBranch,
  'x-circle': XCircle,
  link: Link2,
  percent: Percent,
  'file-warning': FileWarning,
  ban: Ban,
  'file-spreadsheet': FileSpreadsheet,
  'file-check': FileCheck,
  'users-round': UsersRound,
  'file-input': FileInput,
  'file-search': FileSearch,
  'file-plus': FilePlus,
  sparkles: Sparkles,
  gift: Gift,
  factory: Factory,
  'shopping-cart': ShoppingCart,
  'hard-hat': HardHat,
  cpu: Cpu,
}

export function DocIcon({ name, size = 22, className = '' }) {
  const Icon = MAP[name] || FileText
  return <Icon size={size} className={className} strokeWidth={1.75} />
}

export {
  Bookmark,
  BookmarkCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Download,
  Eye,
  EyeOff,
  LogIn,
  LogOut,
  Maximize2,
  Menu,
  Minimize2,
  Phone,
  Printer,
  RotateCcw,
  Search,
  Settings,
  UserRound,
  X,
  ZoomIn,
  ZoomOut,
}
